name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate multiple snake variants
        uses: Platane/snk@v3
        with:
          github_user_name: Mattos-Soph
          outputs: |
            dist/snake-pink.svg?color_snake=F8C8DC&color_dots=#FFE5EF,#FFC9DE,#FFABC9,#FF8BB3,#FF6A9D
            dist/snake.svg?palette=github-light
            dist/snake-dark.svg?palette=github-dark
            dist/snake-pink.gif?color_snake=F8C8DC&color_dots=#FFE5EF,#FFC9DE,#FFABC9,#FF8BB3,#FF6A9D

      - name: Push snake files to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
