name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: Mattos-Soph
          outputs: |
            dist/snake-pink.svg?color_snake=#FFCBD6&color_dots=#5A4B63,#F8C8DC,#F3A6C1,#ED82AA,#E85D94
            dist/snake-pink.gif?color_snake=#FFCBD6&color_dots=#5A4B63,#F8C8DC,#F3A6C1,#ED82AA,#E85D94

            dist/snake.svg?palette=github-light
            dist/snake-dark.svg?palette=github-dark

      - name: Push snake files to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
